services:
  backend:
    build: ./backend
    container_name: hospital-backend
    ports:
      - "8080:8080"
    dns: [8.8.8.8, 8.8.4.4]
    environment:
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - AWS_REGION=${AWS_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
    volumes:
      - uploads-data:/app/uploads
  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_BASE_URL: http://13.51.255.252:8080
        REACT_APP_GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
    container_name: hospital-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
volumes:
  uploads-data:
